export const BAD_USER_ID_ERR = 'BAD_USER_ID_ERR';
export const APPEND_USERID = 'APPEND_USERID';
export const APPEND_USERIDP = 'APPEND_USERIDP';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const RECEIVE_PROFILE_ERR = 'RECEIVE_PROFILE_ERR';

// New api
export const RECEIVE_REG_INFO = 'RECEIVE_REG_INFO';
export const RECEIVE_VER_INFO = 'RECEIVE_VER_INFO';
export const APP_LOADING = 'APP_LOADING';