export const BAD_USER_ID_ERR = 'BAD_USER_ID_ERR';
export const APPEND_USERID = 'APPEND_USERID';
export const APPEND_USERIDP = 'APPEND_USERIDP';

// New api
export const RECEIVE_REG_INFO = 'RECEIVE_REG_INFO';
export const RECEIVE_REG_INFO_ERR = 'RECEIVE_REG_INFO_ERR';
export const RECEIVE_VER_INFO = 'RECEIVE_VER_INFO';
export const RECEIVE_VER_INFO_ERR = 'RECEIVE_VER_INFO_ERR';
export const RECEIVE_ORIGINAL = 'RECEIVE_ORIGINAL';
export const RECEIVE_ORIGINAL_ERROR = 'RECEIVE_ORIGINAL_ERROR';
export const RECEIVE_ORIGINALS_ROWS = 'RECEIVE_ORIGINALS_ROWS';
export const APP_LOADING = 'APP_LOADING';